# -*- coding: utf-8 -*-
"""LLMcharenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XMMjJ2GySdLcP_8I8zvLx-5AXCn8xpT3
"""

!pip install openai

import openai
import os
openai.api_key = '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'

!pip install rdkit
from rdkit import Chem
from rdkit.Chem import AllChem

def generate_compound_suggestion(prompt):
    response = openai.Completion.create(
        engine="davinci",
        prompt=prompt,
        max_tokens=100,
        n=1,
        stop=None,
        temperature=0.7,
    )

    return response.choices[0].text.strip()

sdf_file = '/content/CBLB_inhibitors_vsF.sdf'
molecules = Chem.SDMolSupplier(sdf_file)

smiles_list = [Chem.MolToSmiles(mol) for mol in molecules if mol is not None]

prompt = f"Based on the following SMILES strings of known active compounds, suggest a new compound that is likely to have activity against the CBL-B protein's TKB domain: {input_data}"
suggested_compound = generate_compound_suggestion(prompt)
print(suggested_compound)

